let original=null,data=null;const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function init(){original=await(await fetch('data/catalog.json')).json();data=structuredClone(original);render()}
function render(){renderItems();renderProjects()}
function renderItems(){$('#items').innerHTML=data.items.map((x,i)=>editor(x,i,false)).join('')}
function renderProjects(){$('#projects').innerHTML=data.projects.map((x,i)=>editor(x,i,true)).join('')}
function editor(x,i,project){return `<div class="editor" data-i="${i}" data-project="${project}"><div class="item-title"><h3>${esc(x.name||'New item')}</h3><button class="danger delete">Delete</button></div><div class="row"><div class="field"><label>ID</label><input data-k="id" value="${esc(x.id)}"></div><div class="field"><label>Name</label><input data-k="name" value="${esc(x.name)}"></div></div><div class="row"><div class="field"><label>Company</label><select data-k="company"><option value="artino" ${x.company==='artino'?'selected':''}>Artino</option><option value="inoway" ${x.company==='inoway'?'selected':''}>InoWay</option></select></div><div class="field"><label>Status</label><input data-k="status" value="${esc(x.status||'To verify')}"></div></div>${project?`<div class="field"><label>Client</label><input data-k="client" value="${esc(x.client||'')}"></div>`:`<div class="row"><div class="field"><label>Category ID</label><input data-k="category" value="${esc(x.category||'')}"></div><div class="field"><label>Type</label><input data-k="type" value="${esc(x.type||'Product Family')}"></div></div>`}<div class="field"><label>Summary</label><textarea data-k="summary">${esc(x.summary||'')}</textarea></div><div class="field"><label>Images (one relative path per line)</label><textarea data-k="images">${esc((x.images||[]).join('\n'))}</textarea></div>${!project?`<div class="field"><label>Specs (one per line)</label><textarea data-k="specs">${esc((x.specs||[]).join('\n'))}</textarea></div>`:`<div class="field"><label>Tags (one per line)</label><textarea data-k="tags">${esc((x.tags||[]).join('\n'))}</textarea></div>`}</div>`}
function sync(){document.querySelectorAll('.editor').forEach(el=>{const i=+el.dataset.i,p=el.dataset.project==='true',obj=p?data.projects[i]:data.items[i];el.querySelectorAll('[data-k]').forEach(f=>{const k=f.dataset.k;obj[k]=['images','specs','tags'].includes(k)?f.value.split('\n').map(s=>s.trim()).filter(Boolean):f.value})})}
document.addEventListener('input',e=>{if(e.target.closest('.editor'))sync()});document.addEventListener('click',e=>{const b=e.target.closest('.delete');if(b){const el=b.closest('.editor'),i=+el.dataset.i,p=el.dataset.project==='true';(p?data.projects:data.items).splice(i,1);render()}});
$('#add').onclick=()=>{sync();data.items.push({id:'NEW-'+Date.now(),company:'artino',category:'artino-signage',name:'New Product / Solution',type:'Product Family',status:'To verify',summary:'Add description.',specs:['Add specification'],images:['images/products/new-item.jpg']});render()};$('#addProject').onclick=()=>{sync();data.projects.push({id:'NEW-P-'+Date.now(),company:'artino',name:'New Project',client:'Client / Project',status:'To verify',summary:'Add project description.',images:['images/projects/new-project.jpg'],tags:['tag']});render()};$('#download').onclick=()=>{sync();const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='catalog.json';a.click();URL.revokeObjectURL(a.href)};$('#reset').onclick=()=>{data=structuredClone(original);render()};init();
