#!/usr/bin/env python3
"""Sync catalog.json into script.js and regenerate local file:// image fallbacks."""
import base64
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "catalog.json"
SCRIPT = ROOT / "script.js"
FALLBACKS = ROOT / "image-fallbacks.js"

data = json.loads(DATA.read_text(encoding="utf-8"))
script = SCRIPT.read_text(encoding="utf-8")
serialized = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
new_script, count = re.subn(
    r"const CATALOG_DATA=\{.*?\};",
    "const CATALOG_DATA=" + serialized + ";",
    script,
    count=1,
    flags=re.DOTALL,
)
if count != 1:
    raise SystemExit("Could not find the CATALOG_DATA block in script.js")
SCRIPT.write_text(new_script, encoding="utf-8")

refs = []
for collection in ("items", "projects"):
    for entry in data.get(collection, []):
        for src in entry.get("images", []):
            src = str(src).replace("\\", "/")
            if src and src not in refs:
                refs.append(src)

missing = [src for src in refs if not (ROOT / src).is_file()]
if missing:
    raise SystemExit("Missing referenced images:\n" + "\n".join(missing))

lines = [
    "// Auto-generated by tools/build_catalog.py.",
    "// Used only when the catalog is opened via file://.",
    "window.ARTINO_IMAGE_FALLBACKS = {",
]
for src in refs:
    path = ROOT / src
    mime = "image/jpeg" if path.suffix.lower() in {".jpg", ".jpeg"} else "image/png"
    encoded = base64.b64encode(path.read_bytes()).decode("ascii")
    lines.append(json.dumps(src, ensure_ascii=False) + ":" + json.dumps(f"data:{mime};base64,{encoded}") + ",")
lines.append("};\n")
FALLBACKS.write_text("\n".join(lines), encoding="utf-8")

print(f"SYNCED: {DATA.relative_to(ROOT)} -> {SCRIPT.relative_to(ROOT)}")
print(f"IMAGE FALLBACKS: {len(refs)} referenced images -> {FALLBACKS.relative_to(ROOT)}")
